# Generated by Django 5.0.6 on 2024-09-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_de_custo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'centro_de_custo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntidadeProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'entidade_projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_projeto', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'projeto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('disco', models.CharField(blank=True, max_length=50, null=True)),
                ('vcpu', models.CharField(blank=True, max_length=50, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('so', models.CharField(blank=True, max_length=50, null=True)),
                ('rede', models.CharField(blank=True, max_length=50, null=True)),
                ('ip_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('licenca', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'vm',
                'managed': False,
            },
        ),
    ]
